/* tslint:disable */
/* eslint-disable */
/**
 * OR Planner API
 * Operating Room Planner API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.chromek@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MedicalStaff,
} from '../models';
import {
    MedicalStaffFromJSON,
    MedicalStaffToJSON,
} from '../models';

export interface CreateStaffRequest {
    medicalStaff: MedicalStaff;
}

export interface GetStaffMemberRequest {
    staffId: string;
}

export interface UpdateStaffMemberRequest {
    staffId: string;
    medicalStaff: MedicalStaff;
}

/**
 * MedicalStaffApi - interface
 * 
 * @export
 * @interface MedicalStaffApiInterface
 */
export interface MedicalStaffApiInterface {
    /**
     * 
     * @param {MedicalStaff} medicalStaff 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MedicalStaffApiInterface
     */
    createStaffRaw(requestParameters: CreateStaffRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MedicalStaff>>;

    /**
     */
    createStaff(requestParameters: CreateStaffRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MedicalStaff>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MedicalStaffApiInterface
     */
    getStaffRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MedicalStaff>>>;

    /**
     */
    getStaff(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MedicalStaff>>;

    /**
     * 
     * @param {string} staffId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MedicalStaffApiInterface
     */
    getStaffMemberRaw(requestParameters: GetStaffMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MedicalStaff>>;

    /**
     */
    getStaffMember(requestParameters: GetStaffMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MedicalStaff>;

    /**
     * 
     * @param {string} staffId 
     * @param {MedicalStaff} medicalStaff 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MedicalStaffApiInterface
     */
    updateStaffMemberRaw(requestParameters: UpdateStaffMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MedicalStaff>>;

    /**
     */
    updateStaffMember(requestParameters: UpdateStaffMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MedicalStaff>;

}

/**
 * 
 */
export class MedicalStaffApi extends runtime.BaseAPI implements MedicalStaffApiInterface {

    /**
     */
    async createStaffRaw(requestParameters: CreateStaffRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MedicalStaff>> {
        if (requestParameters.medicalStaff === null || requestParameters.medicalStaff === undefined) {
            throw new runtime.RequiredError('medicalStaff','Required parameter requestParameters.medicalStaff was null or undefined when calling createStaff.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/staff`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MedicalStaffToJSON(requestParameters.medicalStaff),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MedicalStaffFromJSON(jsonValue));
    }

    /**
     */
    async createStaff(requestParameters: CreateStaffRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MedicalStaff> {
        const response = await this.createStaffRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getStaffRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MedicalStaff>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/staff`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MedicalStaffFromJSON));
    }

    /**
     */
    async getStaff(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MedicalStaff>> {
        const response = await this.getStaffRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getStaffMemberRaw(requestParameters: GetStaffMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MedicalStaff>> {
        if (requestParameters.staffId === null || requestParameters.staffId === undefined) {
            throw new runtime.RequiredError('staffId','Required parameter requestParameters.staffId was null or undefined when calling getStaffMember.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/staff/{staffId}`.replace(`{${"staffId"}}`, encodeURIComponent(String(requestParameters.staffId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MedicalStaffFromJSON(jsonValue));
    }

    /**
     */
    async getStaffMember(requestParameters: GetStaffMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MedicalStaff> {
        const response = await this.getStaffMemberRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateStaffMemberRaw(requestParameters: UpdateStaffMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MedicalStaff>> {
        if (requestParameters.staffId === null || requestParameters.staffId === undefined) {
            throw new runtime.RequiredError('staffId','Required parameter requestParameters.staffId was null or undefined when calling updateStaffMember.');
        }

        if (requestParameters.medicalStaff === null || requestParameters.medicalStaff === undefined) {
            throw new runtime.RequiredError('medicalStaff','Required parameter requestParameters.medicalStaff was null or undefined when calling updateStaffMember.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/staff/{staffId}`.replace(`{${"staffId"}}`, encodeURIComponent(String(requestParameters.staffId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: MedicalStaffToJSON(requestParameters.medicalStaff),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MedicalStaffFromJSON(jsonValue));
    }

    /**
     */
    async updateStaffMember(requestParameters: UpdateStaffMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MedicalStaff> {
        const response = await this.updateStaffMemberRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
