/* tslint:disable */
/* eslint-disable */
/**
 * OR Planner API
 * Operating Room Planner API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.chromek@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  OperatingRoom,
} from '../models';
import {
    OperatingRoomFromJSON,
    OperatingRoomToJSON,
} from '../models';

export interface CreateRoomRequest {
    operatingRoom: OperatingRoom;
}

export interface GetRoomRequest {
    roomId: string;
}

export interface UpdateRoomRequest {
    roomId: string;
    operatingRoom: OperatingRoom;
}

/**
 * OperatingRoomsApi - interface
 * 
 * @export
 * @interface OperatingRoomsApiInterface
 */
export interface OperatingRoomsApiInterface {
    /**
     * 
     * @summary Create new operating room
     * @param {OperatingRoom} operatingRoom 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OperatingRoomsApiInterface
     */
    createRoomRaw(requestParameters: CreateRoomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperatingRoom>>;

    /**
     * Create new operating room
     */
    createRoom(requestParameters: CreateRoomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperatingRoom>;

    /**
     * 
     * @param {string} roomId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OperatingRoomsApiInterface
     */
    getRoomRaw(requestParameters: GetRoomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperatingRoom>>;

    /**
     */
    getRoom(requestParameters: GetRoomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperatingRoom>;

    /**
     * 
     * @summary List all operating rooms
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OperatingRoomsApiInterface
     */
    getRoomsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OperatingRoom>>>;

    /**
     * List all operating rooms
     */
    getRooms(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OperatingRoom>>;

    /**
     * 
     * @param {string} roomId 
     * @param {OperatingRoom} operatingRoom 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OperatingRoomsApiInterface
     */
    updateRoomRaw(requestParameters: UpdateRoomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperatingRoom>>;

    /**
     */
    updateRoom(requestParameters: UpdateRoomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperatingRoom>;

}

/**
 * 
 */
export class OperatingRoomsApi extends runtime.BaseAPI implements OperatingRoomsApiInterface {

    /**
     * Create new operating room
     */
    async createRoomRaw(requestParameters: CreateRoomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperatingRoom>> {
        if (requestParameters.operatingRoom === null || requestParameters.operatingRoom === undefined) {
            throw new runtime.RequiredError('operatingRoom','Required parameter requestParameters.operatingRoom was null or undefined when calling createRoom.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/rooms`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OperatingRoomToJSON(requestParameters.operatingRoom),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OperatingRoomFromJSON(jsonValue));
    }

    /**
     * Create new operating room
     */
    async createRoom(requestParameters: CreateRoomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperatingRoom> {
        const response = await this.createRoomRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getRoomRaw(requestParameters: GetRoomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperatingRoom>> {
        if (requestParameters.roomId === null || requestParameters.roomId === undefined) {
            throw new runtime.RequiredError('roomId','Required parameter requestParameters.roomId was null or undefined when calling getRoom.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rooms/{roomId}`.replace(`{${"roomId"}}`, encodeURIComponent(String(requestParameters.roomId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OperatingRoomFromJSON(jsonValue));
    }

    /**
     */
    async getRoom(requestParameters: GetRoomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperatingRoom> {
        const response = await this.getRoomRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all operating rooms
     */
    async getRoomsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OperatingRoom>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rooms`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OperatingRoomFromJSON));
    }

    /**
     * List all operating rooms
     */
    async getRooms(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OperatingRoom>> {
        const response = await this.getRoomsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async updateRoomRaw(requestParameters: UpdateRoomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperatingRoom>> {
        if (requestParameters.roomId === null || requestParameters.roomId === undefined) {
            throw new runtime.RequiredError('roomId','Required parameter requestParameters.roomId was null or undefined when calling updateRoom.');
        }

        if (requestParameters.operatingRoom === null || requestParameters.operatingRoom === undefined) {
            throw new runtime.RequiredError('operatingRoom','Required parameter requestParameters.operatingRoom was null or undefined when calling updateRoom.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/rooms/{roomId}`.replace(`{${"roomId"}}`, encodeURIComponent(String(requestParameters.roomId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: OperatingRoomToJSON(requestParameters.operatingRoom),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OperatingRoomFromJSON(jsonValue));
    }

    /**
     */
    async updateRoom(requestParameters: UpdateRoomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperatingRoom> {
        const response = await this.updateRoomRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
