/* tslint:disable */
/* eslint-disable */
/**
 * OR Planner API
 * Operating Room Planner API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.chromek@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ScheduledOperation,
} from '../models';
import {
    ScheduledOperationFromJSON,
    ScheduledOperationToJSON,
} from '../models';

export interface CreateOperationRequest {
    roomId: string;
    scheduledOperation: ScheduledOperation;
}

export interface DeleteOperationRequest {
    roomId: string;
    opId: string;
}

export interface GetOperationRequest {
    roomId: string;
    opId: string;
}

export interface GetRoomOperationsRequest {
    roomId: string;
}

export interface UpdateOperationRequest {
    roomId: string;
    opId: string;
    scheduledOperation: ScheduledOperation;
}

/**
 * ScheduledOperationsApi - interface
 * 
 * @export
 * @interface ScheduledOperationsApiInterface
 */
export interface ScheduledOperationsApiInterface {
    /**
     * 
     * @param {string} roomId 
     * @param {ScheduledOperation} scheduledOperation 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ScheduledOperationsApiInterface
     */
    createOperationRaw(requestParameters: CreateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduledOperation>>;

    /**
     */
    createOperation(requestParameters: CreateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduledOperation>;

    /**
     * 
     * @param {string} roomId 
     * @param {string} opId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ScheduledOperationsApiInterface
     */
    deleteOperationRaw(requestParameters: DeleteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    deleteOperation(requestParameters: DeleteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} roomId 
     * @param {string} opId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ScheduledOperationsApiInterface
     */
    getOperationRaw(requestParameters: GetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduledOperation>>;

    /**
     */
    getOperation(requestParameters: GetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduledOperation>;

    /**
     * 
     * @param {string} roomId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ScheduledOperationsApiInterface
     */
    getRoomOperationsRaw(requestParameters: GetRoomOperationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ScheduledOperation>>>;

    /**
     */
    getRoomOperations(requestParameters: GetRoomOperationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ScheduledOperation>>;

    /**
     * 
     * @param {string} roomId 
     * @param {string} opId 
     * @param {ScheduledOperation} scheduledOperation 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ScheduledOperationsApiInterface
     */
    updateOperationRaw(requestParameters: UpdateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduledOperation>>;

    /**
     */
    updateOperation(requestParameters: UpdateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduledOperation>;

}

/**
 * 
 */
export class ScheduledOperationsApi extends runtime.BaseAPI implements ScheduledOperationsApiInterface {

    /**
     */
    async createOperationRaw(requestParameters: CreateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduledOperation>> {
        if (requestParameters.roomId === null || requestParameters.roomId === undefined) {
            throw new runtime.RequiredError('roomId','Required parameter requestParameters.roomId was null or undefined when calling createOperation.');
        }

        if (requestParameters.scheduledOperation === null || requestParameters.scheduledOperation === undefined) {
            throw new runtime.RequiredError('scheduledOperation','Required parameter requestParameters.scheduledOperation was null or undefined when calling createOperation.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/rooms/{roomId}/operations`.replace(`{${"roomId"}}`, encodeURIComponent(String(requestParameters.roomId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ScheduledOperationToJSON(requestParameters.scheduledOperation),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduledOperationFromJSON(jsonValue));
    }

    /**
     */
    async createOperation(requestParameters: CreateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduledOperation> {
        const response = await this.createOperationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteOperationRaw(requestParameters: DeleteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.roomId === null || requestParameters.roomId === undefined) {
            throw new runtime.RequiredError('roomId','Required parameter requestParameters.roomId was null or undefined when calling deleteOperation.');
        }

        if (requestParameters.opId === null || requestParameters.opId === undefined) {
            throw new runtime.RequiredError('opId','Required parameter requestParameters.opId was null or undefined when calling deleteOperation.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rooms/{roomId}/operations/{opId}`.replace(`{${"roomId"}}`, encodeURIComponent(String(requestParameters.roomId))).replace(`{${"opId"}}`, encodeURIComponent(String(requestParameters.opId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteOperation(requestParameters: DeleteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteOperationRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getOperationRaw(requestParameters: GetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduledOperation>> {
        if (requestParameters.roomId === null || requestParameters.roomId === undefined) {
            throw new runtime.RequiredError('roomId','Required parameter requestParameters.roomId was null or undefined when calling getOperation.');
        }

        if (requestParameters.opId === null || requestParameters.opId === undefined) {
            throw new runtime.RequiredError('opId','Required parameter requestParameters.opId was null or undefined when calling getOperation.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rooms/{roomId}/operations/{opId}`.replace(`{${"roomId"}}`, encodeURIComponent(String(requestParameters.roomId))).replace(`{${"opId"}}`, encodeURIComponent(String(requestParameters.opId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduledOperationFromJSON(jsonValue));
    }

    /**
     */
    async getOperation(requestParameters: GetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduledOperation> {
        const response = await this.getOperationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getRoomOperationsRaw(requestParameters: GetRoomOperationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ScheduledOperation>>> {
        if (requestParameters.roomId === null || requestParameters.roomId === undefined) {
            throw new runtime.RequiredError('roomId','Required parameter requestParameters.roomId was null or undefined when calling getRoomOperations.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rooms/{roomId}/operations`.replace(`{${"roomId"}}`, encodeURIComponent(String(requestParameters.roomId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ScheduledOperationFromJSON));
    }

    /**
     */
    async getRoomOperations(requestParameters: GetRoomOperationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ScheduledOperation>> {
        const response = await this.getRoomOperationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateOperationRaw(requestParameters: UpdateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduledOperation>> {
        if (requestParameters.roomId === null || requestParameters.roomId === undefined) {
            throw new runtime.RequiredError('roomId','Required parameter requestParameters.roomId was null or undefined when calling updateOperation.');
        }

        if (requestParameters.opId === null || requestParameters.opId === undefined) {
            throw new runtime.RequiredError('opId','Required parameter requestParameters.opId was null or undefined when calling updateOperation.');
        }

        if (requestParameters.scheduledOperation === null || requestParameters.scheduledOperation === undefined) {
            throw new runtime.RequiredError('scheduledOperation','Required parameter requestParameters.scheduledOperation was null or undefined when calling updateOperation.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/rooms/{roomId}/operations/{opId}`.replace(`{${"roomId"}}`, encodeURIComponent(String(requestParameters.roomId))).replace(`{${"opId"}}`, encodeURIComponent(String(requestParameters.opId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ScheduledOperationToJSON(requestParameters.scheduledOperation),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduledOperationFromJSON(jsonValue));
    }

    /**
     */
    async updateOperation(requestParameters: UpdateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduledOperation> {
        const response = await this.updateOperationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
