/* tslint:disable */
/* eslint-disable */
/**
 * OR Planner API
 * Operating Room Planner API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.chromek@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MedicalStaffAvailabilityInner
 */
export interface MedicalStaffAvailabilityInner {
    /**
     * 
     * @type {Date}
     * @memberof MedicalStaffAvailabilityInner
     */
    from: Date;
    /**
     * 
     * @type {Date}
     * @memberof MedicalStaffAvailabilityInner
     */
    to: Date;
}

/**
 * Check if a given object implements the MedicalStaffAvailabilityInner interface.
 */
export function instanceOfMedicalStaffAvailabilityInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "from" in value;
    isInstance = isInstance && "to" in value;

    return isInstance;
}

export function MedicalStaffAvailabilityInnerFromJSON(json: any): MedicalStaffAvailabilityInner {
    return MedicalStaffAvailabilityInnerFromJSONTyped(json, false);
}

export function MedicalStaffAvailabilityInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MedicalStaffAvailabilityInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'from': (new Date(json['from'])),
        'to': (new Date(json['to'])),
    };
}

export function MedicalStaffAvailabilityInnerToJSON(value?: MedicalStaffAvailabilityInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'from': (value.from.toISOString()),
        'to': (value.to.toISOString()),
    };
}

