/* tslint:disable */
/* eslint-disable */
/**
 * OR Planner API
 * Operating Room Planner API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.chromek@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProcedureType } from './ProcedureType';
import {
    ProcedureTypeFromJSON,
    ProcedureTypeFromJSONTyped,
    ProcedureTypeToJSON,
} from './ProcedureType';
import type { ScheduledOperation } from './ScheduledOperation';
import {
    ScheduledOperationFromJSON,
    ScheduledOperationFromJSONTyped,
    ScheduledOperationToJSON,
} from './ScheduledOperation';

/**
 * 
 * @export
 * @interface OperatingRoom
 */
export interface OperatingRoom {
    /**
     * 
     * @type {string}
     * @memberof OperatingRoom
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OperatingRoom
     */
    number: string;
    /**
     * 
     * @type {string}
     * @memberof OperatingRoom
     */
    name: string;
    /**
     * general, cardiac, orthopedic, etc.
     * @type {string}
     * @memberof OperatingRoom
     */
    type?: string;
    /**
     * 
     * @type {number}
     * @memberof OperatingRoom
     */
    capacity?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof OperatingRoom
     */
    equipment?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof OperatingRoom
     */
    status: OperatingRoomStatusEnum;
    /**
     * 
     * @type {Array<ScheduledOperation>}
     * @memberof OperatingRoom
     */
    scheduledOperations?: Array<ScheduledOperation>;
    /**
     * 
     * @type {Array<ProcedureType>}
     * @memberof OperatingRoom
     */
    predefinedProcedures?: Array<ProcedureType>;
    /**
     * 
     * @type {boolean}
     * @memberof OperatingRoom
     */
    archived?: boolean;
}


/**
 * @export
 */
export const OperatingRoomStatusEnum = {
    Active: 'active',
    Maintenance: 'maintenance',
    Inactive: 'inactive'
} as const;
export type OperatingRoomStatusEnum = typeof OperatingRoomStatusEnum[keyof typeof OperatingRoomStatusEnum];


/**
 * Check if a given object implements the OperatingRoom interface.
 */
export function instanceOfOperatingRoom(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "number" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function OperatingRoomFromJSON(json: any): OperatingRoom {
    return OperatingRoomFromJSONTyped(json, false);
}

export function OperatingRoomFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperatingRoom {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'number': json['number'],
        'name': json['name'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'capacity': !exists(json, 'capacity') ? undefined : json['capacity'],
        'equipment': !exists(json, 'equipment') ? undefined : json['equipment'],
        'status': json['status'],
        'scheduledOperations': !exists(json, 'scheduledOperations') ? undefined : ((json['scheduledOperations'] as Array<any>).map(ScheduledOperationFromJSON)),
        'predefinedProcedures': !exists(json, 'predefinedProcedures') ? undefined : ((json['predefinedProcedures'] as Array<any>).map(ProcedureTypeFromJSON)),
        'archived': !exists(json, 'archived') ? undefined : json['archived'],
    };
}

export function OperatingRoomToJSON(value?: OperatingRoom | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'number': value.number,
        'name': value.name,
        'type': value.type,
        'capacity': value.capacity,
        'equipment': value.equipment,
        'status': value.status,
        'scheduledOperations': value.scheduledOperations === undefined ? undefined : ((value.scheduledOperations as Array<any>).map(ScheduledOperationToJSON)),
        'predefinedProcedures': value.predefinedProcedures === undefined ? undefined : ((value.predefinedProcedures as Array<any>).map(ProcedureTypeToJSON)),
        'archived': value.archived,
    };
}

