/* tslint:disable */
/* eslint-disable */
/**
 * OR Planner API
 * Operating Room Planner API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.chromek@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProcedureType
 */
export interface ProcedureType {
    /**
     * 
     * @type {string}
     * @memberof ProcedureType
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof ProcedureType
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ProcedureType
     */
    typicalDurationMinutes?: number;
}

/**
 * Check if a given object implements the ProcedureType interface.
 */
export function instanceOfProcedureType(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function ProcedureTypeFromJSON(json: any): ProcedureType {
    return ProcedureTypeFromJSONTyped(json, false);
}

export function ProcedureTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcedureType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'name': json['name'],
        'typicalDurationMinutes': !exists(json, 'typicalDurationMinutes') ? undefined : json['typicalDurationMinutes'],
    };
}

export function ProcedureTypeToJSON(value?: ProcedureType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'name': value.name,
        'typicalDurationMinutes': value.typicalDurationMinutes,
    };
}

