/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface OrpOperationEditor {
        "apiBase": string;
        "entryId": string;
        "roomId": string;
    }
    interface OrpOperationList {
        "apiBase": string;
        "roomId": string;
    }
    interface OrpOrApp {
        "apiBase": string;
        /**
          * @default ""
         */
        "basePath": string;
    }
    interface OrpPatientEditor {
        "apiBase": string;
        "entryId": string;
    }
    interface OrpPatientsList {
        "apiBase": string;
    }
    interface OrpRoomEditor {
        "apiBase": string;
        "entryId": string;
    }
    interface OrpRoomsList {
        "apiBase": string;
    }
    interface OrpStaffEditor {
        "apiBase": string;
        "entryId": string;
    }
    interface OrpStaffList {
        "apiBase": string;
    }
}
export interface OrpOperationEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOrpOperationEditorElement;
}
export interface OrpOperationListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOrpOperationListElement;
}
export interface OrpPatientEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOrpPatientEditorElement;
}
export interface OrpPatientsListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOrpPatientsListElement;
}
export interface OrpRoomEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOrpRoomEditorElement;
}
export interface OrpRoomsListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOrpRoomsListElement;
}
export interface OrpStaffEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOrpStaffEditorElement;
}
export interface OrpStaffListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOrpStaffListElement;
}
declare global {
    interface HTMLOrpOperationEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLOrpOperationEditorElement extends Components.OrpOperationEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOrpOperationEditorElementEventMap>(type: K, listener: (this: HTMLOrpOperationEditorElement, ev: OrpOperationEditorCustomEvent<HTMLOrpOperationEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOrpOperationEditorElementEventMap>(type: K, listener: (this: HTMLOrpOperationEditorElement, ev: OrpOperationEditorCustomEvent<HTMLOrpOperationEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOrpOperationEditorElement: {
        prototype: HTMLOrpOperationEditorElement;
        new (): HTMLOrpOperationEditorElement;
    };
    interface HTMLOrpOperationListElementEventMap {
        "entry-clicked": string;
        "back-clicked": void;
    }
    interface HTMLOrpOperationListElement extends Components.OrpOperationList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOrpOperationListElementEventMap>(type: K, listener: (this: HTMLOrpOperationListElement, ev: OrpOperationListCustomEvent<HTMLOrpOperationListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOrpOperationListElementEventMap>(type: K, listener: (this: HTMLOrpOperationListElement, ev: OrpOperationListCustomEvent<HTMLOrpOperationListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOrpOperationListElement: {
        prototype: HTMLOrpOperationListElement;
        new (): HTMLOrpOperationListElement;
    };
    interface HTMLOrpOrAppElement extends Components.OrpOrApp, HTMLStencilElement {
    }
    var HTMLOrpOrAppElement: {
        prototype: HTMLOrpOrAppElement;
        new (): HTMLOrpOrAppElement;
    };
    interface HTMLOrpPatientEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLOrpPatientEditorElement extends Components.OrpPatientEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOrpPatientEditorElementEventMap>(type: K, listener: (this: HTMLOrpPatientEditorElement, ev: OrpPatientEditorCustomEvent<HTMLOrpPatientEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOrpPatientEditorElementEventMap>(type: K, listener: (this: HTMLOrpPatientEditorElement, ev: OrpPatientEditorCustomEvent<HTMLOrpPatientEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOrpPatientEditorElement: {
        prototype: HTMLOrpPatientEditorElement;
        new (): HTMLOrpPatientEditorElement;
    };
    interface HTMLOrpPatientsListElementEventMap {
        "entry-clicked": string;
    }
    interface HTMLOrpPatientsListElement extends Components.OrpPatientsList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOrpPatientsListElementEventMap>(type: K, listener: (this: HTMLOrpPatientsListElement, ev: OrpPatientsListCustomEvent<HTMLOrpPatientsListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOrpPatientsListElementEventMap>(type: K, listener: (this: HTMLOrpPatientsListElement, ev: OrpPatientsListCustomEvent<HTMLOrpPatientsListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOrpPatientsListElement: {
        prototype: HTMLOrpPatientsListElement;
        new (): HTMLOrpPatientsListElement;
    };
    interface HTMLOrpRoomEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLOrpRoomEditorElement extends Components.OrpRoomEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOrpRoomEditorElementEventMap>(type: K, listener: (this: HTMLOrpRoomEditorElement, ev: OrpRoomEditorCustomEvent<HTMLOrpRoomEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOrpRoomEditorElementEventMap>(type: K, listener: (this: HTMLOrpRoomEditorElement, ev: OrpRoomEditorCustomEvent<HTMLOrpRoomEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOrpRoomEditorElement: {
        prototype: HTMLOrpRoomEditorElement;
        new (): HTMLOrpRoomEditorElement;
    };
    interface HTMLOrpRoomsListElementEventMap {
        "entry-clicked": string;
    }
    interface HTMLOrpRoomsListElement extends Components.OrpRoomsList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOrpRoomsListElementEventMap>(type: K, listener: (this: HTMLOrpRoomsListElement, ev: OrpRoomsListCustomEvent<HTMLOrpRoomsListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOrpRoomsListElementEventMap>(type: K, listener: (this: HTMLOrpRoomsListElement, ev: OrpRoomsListCustomEvent<HTMLOrpRoomsListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOrpRoomsListElement: {
        prototype: HTMLOrpRoomsListElement;
        new (): HTMLOrpRoomsListElement;
    };
    interface HTMLOrpStaffEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLOrpStaffEditorElement extends Components.OrpStaffEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOrpStaffEditorElementEventMap>(type: K, listener: (this: HTMLOrpStaffEditorElement, ev: OrpStaffEditorCustomEvent<HTMLOrpStaffEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOrpStaffEditorElementEventMap>(type: K, listener: (this: HTMLOrpStaffEditorElement, ev: OrpStaffEditorCustomEvent<HTMLOrpStaffEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOrpStaffEditorElement: {
        prototype: HTMLOrpStaffEditorElement;
        new (): HTMLOrpStaffEditorElement;
    };
    interface HTMLOrpStaffListElementEventMap {
        "entry-clicked": string;
    }
    interface HTMLOrpStaffListElement extends Components.OrpStaffList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOrpStaffListElementEventMap>(type: K, listener: (this: HTMLOrpStaffListElement, ev: OrpStaffListCustomEvent<HTMLOrpStaffListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOrpStaffListElementEventMap>(type: K, listener: (this: HTMLOrpStaffListElement, ev: OrpStaffListCustomEvent<HTMLOrpStaffListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOrpStaffListElement: {
        prototype: HTMLOrpStaffListElement;
        new (): HTMLOrpStaffListElement;
    };
    interface HTMLElementTagNameMap {
        "orp-operation-editor": HTMLOrpOperationEditorElement;
        "orp-operation-list": HTMLOrpOperationListElement;
        "orp-or-app": HTMLOrpOrAppElement;
        "orp-patient-editor": HTMLOrpPatientEditorElement;
        "orp-patients-list": HTMLOrpPatientsListElement;
        "orp-room-editor": HTMLOrpRoomEditorElement;
        "orp-rooms-list": HTMLOrpRoomsListElement;
        "orp-staff-editor": HTMLOrpStaffEditorElement;
        "orp-staff-list": HTMLOrpStaffListElement;
    }
}
declare namespace LocalJSX {
    interface OrpOperationEditor {
        "apiBase"?: string;
        "entryId"?: string;
        "onEditor-closed"?: (event: OrpOperationEditorCustomEvent<string>) => void;
        "roomId"?: string;
    }
    interface OrpOperationList {
        "apiBase"?: string;
        "onBack-clicked"?: (event: OrpOperationListCustomEvent<void>) => void;
        "onEntry-clicked"?: (event: OrpOperationListCustomEvent<string>) => void;
        "roomId"?: string;
    }
    interface OrpOrApp {
        "apiBase"?: string;
        /**
          * @default ""
         */
        "basePath"?: string;
    }
    interface OrpPatientEditor {
        "apiBase"?: string;
        "entryId"?: string;
        "onEditor-closed"?: (event: OrpPatientEditorCustomEvent<string>) => void;
    }
    interface OrpPatientsList {
        "apiBase"?: string;
        "onEntry-clicked"?: (event: OrpPatientsListCustomEvent<string>) => void;
    }
    interface OrpRoomEditor {
        "apiBase"?: string;
        "entryId"?: string;
        "onEditor-closed"?: (event: OrpRoomEditorCustomEvent<string>) => void;
    }
    interface OrpRoomsList {
        "apiBase"?: string;
        "onEntry-clicked"?: (event: OrpRoomsListCustomEvent<string>) => void;
    }
    interface OrpStaffEditor {
        "apiBase"?: string;
        "entryId"?: string;
        "onEditor-closed"?: (event: OrpStaffEditorCustomEvent<string>) => void;
    }
    interface OrpStaffList {
        "apiBase"?: string;
        "onEntry-clicked"?: (event: OrpStaffListCustomEvent<string>) => void;
    }

    interface OrpOperationEditorAttributes {
        "entryId": string;
        "roomId": string;
        "apiBase": string;
    }
    interface OrpOperationListAttributes {
        "apiBase": string;
        "roomId": string;
    }
    interface OrpOrAppAttributes {
        "basePath": string;
        "apiBase": string;
    }
    interface OrpPatientEditorAttributes {
        "entryId": string;
        "apiBase": string;
    }
    interface OrpPatientsListAttributes {
        "apiBase": string;
    }
    interface OrpRoomEditorAttributes {
        "entryId": string;
        "apiBase": string;
    }
    interface OrpRoomsListAttributes {
        "apiBase": string;
    }
    interface OrpStaffEditorAttributes {
        "entryId": string;
        "apiBase": string;
    }
    interface OrpStaffListAttributes {
        "apiBase": string;
    }

    interface IntrinsicElements {
        "orp-operation-editor": Omit<OrpOperationEditor, keyof OrpOperationEditorAttributes> & { [K in keyof OrpOperationEditor & keyof OrpOperationEditorAttributes]?: OrpOperationEditor[K] } & { [K in keyof OrpOperationEditor & keyof OrpOperationEditorAttributes as `attr:${K}`]?: OrpOperationEditorAttributes[K] } & { [K in keyof OrpOperationEditor & keyof OrpOperationEditorAttributes as `prop:${K}`]?: OrpOperationEditor[K] };
        "orp-operation-list": Omit<OrpOperationList, keyof OrpOperationListAttributes> & { [K in keyof OrpOperationList & keyof OrpOperationListAttributes]?: OrpOperationList[K] } & { [K in keyof OrpOperationList & keyof OrpOperationListAttributes as `attr:${K}`]?: OrpOperationListAttributes[K] } & { [K in keyof OrpOperationList & keyof OrpOperationListAttributes as `prop:${K}`]?: OrpOperationList[K] };
        "orp-or-app": Omit<OrpOrApp, keyof OrpOrAppAttributes> & { [K in keyof OrpOrApp & keyof OrpOrAppAttributes]?: OrpOrApp[K] } & { [K in keyof OrpOrApp & keyof OrpOrAppAttributes as `attr:${K}`]?: OrpOrAppAttributes[K] } & { [K in keyof OrpOrApp & keyof OrpOrAppAttributes as `prop:${K}`]?: OrpOrApp[K] };
        "orp-patient-editor": Omit<OrpPatientEditor, keyof OrpPatientEditorAttributes> & { [K in keyof OrpPatientEditor & keyof OrpPatientEditorAttributes]?: OrpPatientEditor[K] } & { [K in keyof OrpPatientEditor & keyof OrpPatientEditorAttributes as `attr:${K}`]?: OrpPatientEditorAttributes[K] } & { [K in keyof OrpPatientEditor & keyof OrpPatientEditorAttributes as `prop:${K}`]?: OrpPatientEditor[K] };
        "orp-patients-list": Omit<OrpPatientsList, keyof OrpPatientsListAttributes> & { [K in keyof OrpPatientsList & keyof OrpPatientsListAttributes]?: OrpPatientsList[K] } & { [K in keyof OrpPatientsList & keyof OrpPatientsListAttributes as `attr:${K}`]?: OrpPatientsListAttributes[K] } & { [K in keyof OrpPatientsList & keyof OrpPatientsListAttributes as `prop:${K}`]?: OrpPatientsList[K] };
        "orp-room-editor": Omit<OrpRoomEditor, keyof OrpRoomEditorAttributes> & { [K in keyof OrpRoomEditor & keyof OrpRoomEditorAttributes]?: OrpRoomEditor[K] } & { [K in keyof OrpRoomEditor & keyof OrpRoomEditorAttributes as `attr:${K}`]?: OrpRoomEditorAttributes[K] } & { [K in keyof OrpRoomEditor & keyof OrpRoomEditorAttributes as `prop:${K}`]?: OrpRoomEditor[K] };
        "orp-rooms-list": Omit<OrpRoomsList, keyof OrpRoomsListAttributes> & { [K in keyof OrpRoomsList & keyof OrpRoomsListAttributes]?: OrpRoomsList[K] } & { [K in keyof OrpRoomsList & keyof OrpRoomsListAttributes as `attr:${K}`]?: OrpRoomsListAttributes[K] } & { [K in keyof OrpRoomsList & keyof OrpRoomsListAttributes as `prop:${K}`]?: OrpRoomsList[K] };
        "orp-staff-editor": Omit<OrpStaffEditor, keyof OrpStaffEditorAttributes> & { [K in keyof OrpStaffEditor & keyof OrpStaffEditorAttributes]?: OrpStaffEditor[K] } & { [K in keyof OrpStaffEditor & keyof OrpStaffEditorAttributes as `attr:${K}`]?: OrpStaffEditorAttributes[K] } & { [K in keyof OrpStaffEditor & keyof OrpStaffEditorAttributes as `prop:${K}`]?: OrpStaffEditor[K] };
        "orp-staff-list": Omit<OrpStaffList, keyof OrpStaffListAttributes> & { [K in keyof OrpStaffList & keyof OrpStaffListAttributes]?: OrpStaffList[K] } & { [K in keyof OrpStaffList & keyof OrpStaffListAttributes as `attr:${K}`]?: OrpStaffListAttributes[K] } & { [K in keyof OrpStaffList & keyof OrpStaffListAttributes as `prop:${K}`]?: OrpStaffList[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "orp-operation-editor": LocalJSX.IntrinsicElements["orp-operation-editor"] & JSXBase.HTMLAttributes<HTMLOrpOperationEditorElement>;
            "orp-operation-list": LocalJSX.IntrinsicElements["orp-operation-list"] & JSXBase.HTMLAttributes<HTMLOrpOperationListElement>;
            "orp-or-app": LocalJSX.IntrinsicElements["orp-or-app"] & JSXBase.HTMLAttributes<HTMLOrpOrAppElement>;
            "orp-patient-editor": LocalJSX.IntrinsicElements["orp-patient-editor"] & JSXBase.HTMLAttributes<HTMLOrpPatientEditorElement>;
            "orp-patients-list": LocalJSX.IntrinsicElements["orp-patients-list"] & JSXBase.HTMLAttributes<HTMLOrpPatientsListElement>;
            "orp-room-editor": LocalJSX.IntrinsicElements["orp-room-editor"] & JSXBase.HTMLAttributes<HTMLOrpRoomEditorElement>;
            "orp-rooms-list": LocalJSX.IntrinsicElements["orp-rooms-list"] & JSXBase.HTMLAttributes<HTMLOrpRoomsListElement>;
            "orp-staff-editor": LocalJSX.IntrinsicElements["orp-staff-editor"] & JSXBase.HTMLAttributes<HTMLOrpStaffEditorElement>;
            "orp-staff-list": LocalJSX.IntrinsicElements["orp-staff-list"] & JSXBase.HTMLAttributes<HTMLOrpStaffListElement>;
        }
    }
}
